// Do not edit this file.

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include <errno.h>
#include "memory_system.h"

static FILE *log_file;

int
main() {
  int virt_address;
  int phy_address;
  start_logging();
  
  atexit(teardown);
  initialize();

  printf("> ");
  virt_address = get_int();
  while (virt_address >= 0) {
     if(virt_address != INT_MAX) { // Not a comment
// While loop that takes the input virtual address, maps it to
// a physical address, and then does a lookup to get the corresponding
// byte.
       log_entry(NEW_ADDRESS,virt_address);

       phy_address = get_physical_address(virt_address);   // implement this function
// Assumes function returns -1 if address is illegal 
       if (phy_address != -1) {
          char ch = get_byte(phy_address);  // implement this function
       }
     }
     printf("> ");
     virt_address = get_int();
  }
  stop_logging();
}

int get_int() {
  int val;
  char input_buf[IN_BUF_SIZE];
  char *endptr;

  fgets(input_buf, IN_BUF_SIZE, stdin);
  errno = 0;
  val = (int)strtol(input_buf, &endptr, 10);
  if(errno != 0) {
    exit(-1);
  }
  else if(endptr == input_buf) {
    if(input_buf[0] == '#') { // Check if it's just a comment
      input_buf[strcspn(input_buf, "\n")] = 0;
      printf("%s\n", input_buf);
      val = INT_MAX;
    } else {
      printf("Bad Input Detected.  Ending the Program\n");
      exit(-1);
    }   
  }
  return val;
}

void start_logging() {
   log_file = fopen("project3_logfile","w");
}

void stop_logging() {
   fclose(log_file);
}

/* you can add other types of logging but be sure to disable this before
 * submitting
 */

void log_entry(int type, int data) {
   switch (type) {
     case NEW_ADDRESS:
  	fprintf(log_file,"Virtual Address: 0x%x \n",data); break;
     case DATA_FROM_MEMORY:
  	fprintf(log_file,"\tData: 0x%x from memory\n",data & 0xFF); break;
     case DATA_FROM_CACHE:
  	fprintf(log_file,"\tData: 0x%x from cache\n",data & 0xFF); break;
     case PAGEFAULT:
	fprintf(log_file,"\tPhysical Address: 0x%x from Page Fault Handler\n", data); break;
     case ADDRESS_FROM_PAGETABLE:
  	fprintf(log_file,"\tPhysical Address: 0x%x from Page Table\n",data); break;
     case ADDRESS_FROM_TLB:
  	fprintf(log_file,"\tPhysical Address: 0x%x from TLB\n",data); break;
     case ILLEGALVPN:
  	fprintf(log_file,"\tIllegal VPN generated: 0x%x \n",data); break;
     case PHYSICALERROR:
  	fprintf(log_file,"\tIllegal Physical Address generated: 0x%x \n",data); break;
     case ILLEGALVIRTUAL:
  	fprintf(log_file,"\tIllegal Virtual Address as input: 0x%x \n",data); break;
   }
}
